In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'Dataset\extracted_dataset\non-multisegment\non-multisegment_input.csv')

df.head()

,filename,Event,EventTAG,LAT,LON,DEP,LEN_f,WID,Mw,Mo,...,HR-GPS-Data,Hr-GPS-Data,InSAR-Data,Other-Data,SAT-Data,SPOT-Data,hr-GPS-Data,inSAR-Data,level-Data,tril-Data
0,s1906SANFRA01SONG.fsp,San Francisco (Calif.),s1906SANFRA01SONG,37.78,-122.51,10.0,480.0,12.0,7.91,8.150000e+20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s1906SANFRA01THAT.fsp,San Francisco (Calif.),s1906SANFRA01THAT,37.78,-122.51,10.0,480.0,10.0,7.91,8.120000e+20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s1923KANTOJ01KOBA.fsp,Kanto (Japan),s1923KANTOJ01KOBA,35.40,139.20,14.6,130.0,70.0,8.08,1.460000e+21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s1923KANTOJ01WALD.fsp,Kanto (Japan),s1923KANTOJ01WALD,35.40,139.20,14.6,130.0,70.0,7.95,9.330000e+20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s1944TONANK01ICHI.fsp,Tonankai (Japan),s1944TONANK01ICHI,33.77,135.96,30.0,220.0,140.0,8.04,1.310000e+21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import os

# Path to the folder containing the images
image_folder = r'Dataset\filtered_images_train'

# Check if the folder exists
if os.path.exists(image_folder):
    # Get all files in the folder
    image_files = [f[24:-4] for f in os.listdir(image_folder) if os.path.isfile(os.path.join(image_folder, f))]
    
    # Print the number of files found
    print(f"Found {len(image_files)} files in {image_folder} folder")
    
    # Display the first few filenames
    if image_files:
        print("First 5 filenames:")
        for file in image_files[:5]:
            print(file)
else:
    print(f"The folder '{image_folder}' does not exist.")

Found 161 files in Dataset\filtered_images_train folder
First 5 filenames:
s1923KANTOJ01KOBA.fsp
s1923KANTOJ01WALD.fsp
s1944TONANK01ICHI.fsp
s1944TONANK01KATO.fsp
s1944TONANK01KIKU.fsp

In [4]:
df_cleaned = df[df['filename'].isin(image_files)]

df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 161 entries, 2 to 349
Data columns (total 64 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   filename     161 non-null    object
 1   Event        161 non-null    object
 2   EventTAG     161 non-null    object
 3   LAT          161 non-null    float64
 4   LON          161 non-null    float64
 5   DEP          161 non-null    float64
 6   LEN_f        161 non-null    float64
 7   WID          161 non-null    float64
 8   Mw           161 non-null    float64
 9   Mo           161 non-null    float64
 10  STRK         161 non-null    float64
 11  DIP          161 non-null    float64
 12  RAKE         161 non-null    float64
 13  Htop         161 non-null    float64
 14  HypX         161 non-null    float64
 15  HypZ         161 non-null    float64
 16  avTr         161 non-null    float64
 17  avVr         161 non-null    float64
 18  Nx           161 non-null    float64
 19  Nz           161 non-null    float64
 20  Fmin         161 non-null    float64
 21  Fmax         161 non-null    float64
 22  Dx           161 non-null    float64
 23  Dz           161 non-null    float64
 24  Ntw          161 non-null    float64
 25  Nsg          161 non-null    float64
 26  LEN_inv      161 non-null    float64
 27  SHF          161 non-null    float64
 28  SVF          161 non-null    object
 29  SGM-Data     161 non-null    float64
 30  TELE-Data    161 non-null    float64
 31  TRIL-Data    83 non-null     float64
 32  LEVEL-Data   86 non-null     float64
 33  GPS-Data     161 non-null    float64
 34  INSAR-Data   89 non-null     float64
 35  SURF-Data    80 non-null     float64
 36  OTHER-Data   111 non-null    float64
 37  SGM-PHImx    161 non-null    float64
 38  TELE-PHImx   161 non-null    float64
 39  TRIL-PHImx   161 non-null    float64
 40  LEVEL-PHImx  161 non-null    float64
 41  GPS-PHImx    161 non-null    float64
 42  INSAR-PHImx  158 non-null    float64
 43  SURF-PHImx   157 non-null    float64
 44  OTHER-PHImx  83 non-null     float64
 45  SGM-Rmin     161 non-null    float64
 46  TELE-Rmin    161 non-null    float64
 47  TRIL-Rmin    161 non-null    float64
 48  LEVEL-Rmin   161 non-null    float64
 49  GPS-Rmin     161 non-null    float64
 50  INSAR-Rmin   158 non-null    float64
 51  SURF-Rmin    157 non-null    float64
 52  OTHER-Rmin   83 non-null     float64
 53  BBR-Data     0 non-null      float64
 54  HR-GPS-Data  2 non-null      float64
 55  Hr-GPS-Data  0 non-null      float64
 56  InSAR-Data   70 non-null     float64
 57  Other-Data   15 non-null     float64
 58  SAT-Data     1 non-null      float64
 59  SPOT-Data    0 non-null      float64
 60  hr-GPS-Data  8 non-null      float64
 61  inSAR-Data   0 non-null      float64
 62  level-Data   71 non-null     float64
 63  tril-Data    63 non-null     float64
dtypes: float64(60), object(4)
memory usage: 81.8+ KB

In [5]:
# Get columns with at least one NaN value
cols_with_nan = df_cleaned.columns[df_cleaned.isna().any()].tolist()
print(f"Number of columns with NaN values: {len(cols_with_nan)}")
print(f"Columns with NaN values: {cols_with_nan}")

# Drop columns with at least one NaN value
df_cleaned_no_nan = df_cleaned.dropna(axis=1)

# Check the shape of the new dataframe
print(f"Original shape: {df_cleaned.shape}")
print(f"New shape after dropping NaN columns: {df_cleaned_no_nan.shape}")

# Display the first few rows of the new dataframe
df_cleaned_no_nan.head(3)

Number of columns with NaN values: 22
Columns with NaN values: ['TRIL-Data', 'LEVEL-Data', 'INSAR-Data', 'SURF-Data', 'OTHER-Data', 'INSAR-PHImx', 'SURF-PHImx', 'OTHER-PHImx', 'INSAR-Rmin', 'SURF-Rmin', 'OTHER-Rmin', 'BBR-Data', 'HR-GPS-Data', 'Hr-GPS-Data', 'InSAR-Data', 'Other-Data', 'SAT-Data', 'SPOT-Data', 'hr-GPS-Data', 'inSAR-Data', 'level-Data', 'tril-Data']
Original shape: (161, 64)
New shape after dropping NaN columns: (161, 42)

,filename,Event,EventTAG,LAT,LON,DEP,LEN_f,WID,Mw,Mo,...,SGM-PHImx,TELE-PHImx,TRIL-PHImx,LEVEL-PHImx,GPS-PHImx,SGM-Rmin,TELE-Rmin,TRIL-Rmin,LEVEL-Rmin,GPS-Rmin
2,s1923KANTOJ01KOBA.fsp,Kanto (Japan),s1923KANTOJ01KOBA,35.40,139.20,14.6,130.0,70.0,8.08,1.460000e+21,...,240.0,200.0,999.0,999.0,0.0,90.0,60.0,999.0,999.0,0.0
3,s1923KANTOJ01WALD.fsp,Kanto (Japan),s1923KANTOJ01WALD,35.40,139.20,14.6,130.0,70.0,7.95,9.330000e+20,...,0.0,165.0,0.0,0.0,0.0,0.0,69.8,0.0,0.0,0.0
4,s1944TONANK01ICHI.fsp,Tonankai (Japan),s1944TONANK01ICHI,33.77,135.96,30.0,220.0,140.0,8.04,1.310000e+21,...,180.0,100.0,0.0,0.0,0.0,30.0,60.0,0.0,0.0,0.0

In [6]:
df_cleaned_no_nan.columns

Index(['filename', 'Event', 'EventTAG', 'LAT', 'LON', 'DEP', 'LEN_f', 'WID',
       'Mw', 'Mo', 'STRK', 'DIP', 'RAKE', 'Htop', 'HypX', 'HypZ', 'avTr',
       'avVr', 'Nx', 'Nz', 'Fmin', 'Fmax', 'Dx', 'Dz', 'Ntw', 'Nsg', 'LEN_inv',
       'SHF', 'SVF', 'SGM-Data', 'TELE-Data', 'GPS-Data', 'SGM-PHImx',
       'TELE-PHImx', 'TRIL-PHImx', 'LEVEL-PHImx', 'GPS-PHImx', 'SGM-Rmin',
       'TELE-Rmin', 'TRIL-Rmin', 'LEVEL-Rmin', 'GPS-Rmin'],
      dtype='object')

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import griddata

df = pd.read_csv(r'Dataset\extracted_dataset\non-multisegment\non-multisegment_output.csv')
inv = df_cleaned_no_nan
c = 0
for i in df_cleaned_no_nan['filename'].unique():
    # Find this fault in the original dataframe to get the Dx value
    fault_dx = inv[inv['filename']==i]['Dx'].values[0]
    
    # --- Step 1: Extract & Scale Data ---
    es = df[df['filename']==i]['X==EW'].values * fault_dx/5
    ns = df[df['filename']==i]['Y==NS'].values * fault_dx/5
    slip = df[df['filename']==i]['SLIP'].values / df['SLIP'].max()
    
    print(f"Processing file {i} (count={c})")
    c += 1  # Increment counter

    # --- Step 2: Re-center ---
    es_centered = np.mean(es)
    ns_centered = np.mean(ns)

    dist = (es_centered**2 + ns_centered**2)**0.5
    df_cleaned_no_nan.loc[df_cleaned_no_nan['filename'] == i, 'distance from the epicenter'] = dist

Processing file s1923KANTOJ01KOBA.fsp (count=0)
Processing file s1923KANTOJ01WALD.fsp (count=1)
Processing file s1944TONANK01ICHI.fsp (count=2)
Processing file s1944TONANK01KATO.fsp (count=3)
Processing file s1944TONANK01KIKU.fsp (count=4)
Processing file s1944TONANK01SATA.fsp (count=5)
Processing file s1944TONANK01TANI.fsp (count=6)
Processing file s1946NANKAI01BABA.fsp (count=7)
Processing file s1946NANKAI01KATO.fsp (count=8)
Processing file s1946NANKAI01SATA.fsp (count=9)

C:\Users\atmad\AppData\Local\Temp\ipykernel_11220\441951902.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned_no_nan.loc[df_cleaned_no_nan['filename'] == i, 'distance from the epicenter'] = dist

Processing file s1946NANKAI01TANI.fsp (count=10)
Processing file s1968HYUGAx01YAGI.fsp (count=11)
Processing file s1968TOKACH01NAGA.fsp (count=12)
Processing file s1978MIYAGI01YAMA.fsp (count=13)
Processing file s1978TABASI01HART.fsp (count=14)
Processing file s1979PETATL01MEND.fsp (count=15)
Processing file s1981PLAYAA01MEND.fsp (count=16)
Processing file s1985MICHOA01MEND.fsp (count=17)
Processing file s1985ZIHUAT01MEND.fsp (count=18)
Processing file s1994SANRIK01HAYE.fsp (count=19)
Processing file s1994SANRIK01NAGA.fsp (count=20)
Processing file s1995COLIMA01MEND.fsp (count=21)
Processing file s1995COPALA01COUR.fsp (count=22)
Processing file s1996NAZCAR01HAYE.fsp (count=23)
Processing file s1996NAZCAR01SALI.fsp (count=24)
Processing file s1996NAZCAR01SPEN.fsp (count=25)
Processing file s1998ANTARC02ANTO.fsp (count=26)
Processing file s1999CHICHI01CHIx.fsp (count=27)
Processing file s1999CHICHI01HAYE.fsp (count=28)
Processing file s1999CHICHI01MAxx.fsp (count=29)
Processing file s1999CHICHI02MAxx.fsp (count=30)
Processing file s2003COLIMA01HAYE.fsp (count=31)
Processing file s2003COLIMA01YAGI.fsp (count=32)
Processing file s2003TOKACH01HAYE.fsp (count=33)
Processing file s2003TOKACH01KOKE.fsp (count=34)
Processing file s2003TOKACH01TANI.fsp (count=35)
Processing file s2003TOKACH01YAGI.fsp (count=36)
Processing file s2003TOKACH01YAMA.fsp (count=37)
Processing file s2004SUMATR01JIxx.fsp (count=38)
Processing file s2005HONSHU01SHAO.fsp (count=39)
Processing file s2005KASHMI01SHAO.fsp (count=40)
Processing file s2005SUMATR01JIxx.fsp (count=41)
Processing file s2005SUMATR01KONC.fsp (count=42)
Processing file s2005SUMATR01SHAO.fsp (count=43)
Processing file s2006JAVAIN01HAYE.fsp (count=44)
Processing file s2006JAVAIN01YAGI.fsp (count=45)
Processing file s2006KURILI01HAYE.fsp (count=46)
Processing file s2006KURILI01JIxx.fsp (count=47)
Processing file s2006KURILI01LAYx.fsp (count=48)
Processing file s2006KURILI02SLAD.fsp (count=49)
Processing file s2006PINGTU02YENx.fsp (count=50)
Processing file s2006SOUTHE01JIxx.fsp (count=51)
Processing file s2006SOUTHE01KONC.fsp (count=52)
Processing file s2007BENGKU01GUSM.fsp (count=53)
Processing file s2007BENGKU02GUSM.fsp (count=54)
Processing file s2007BENKUL01HAYE.fsp (count=55)
Processing file s2007BENKUL01JIxx.fsp (count=56)
Processing file s2007BENKUL01KONC.fsp (count=57)
Processing file s2007BENKUL02KONC.fsp (count=58)
Processing file s2007KURILI01HAYE.fsp (count=59)
Processing file s2007MOLUCC01HAYE.fsp (count=60)
Processing file s2007PAGAII01HAYE.fsp (count=61)
Processing file s2007PAGAII01JIxx.fsp (count=62)
Processing file s2007PAGAII01KONC.fsp (count=63)
Processing file s2007PAGAII01SLAD.fsp (count=64)
Processing file s2007PISCOP01JIxx.fsp (count=65)
Processing file s2007PISCOP01KONC.fsp (count=66)
Processing file s2007SOLOMO01JIxx.fsp (count=67)
Processing file s2007SOUTHO01HAYE.fsp (count=68)
Processing file s2007TOCOPI01BEJA.fsp (count=69)
Processing file s2007TOCOPI01HAYE.fsp (count=70)
Processing file s2007TOCOPI01JIxx.fsp (count=71)
Processing file s2007TOCOPI01MOTA.fsp (count=72)
Processing file s2007TOCOPI01SLAD.fsp (count=73)
Processing file s2007TOCOPI01ZENG.fsp (count=74)
Processing file s2007TOCOPI02BEJA.fsp (count=75)
Processing file s2007TOCOPI03BEJA.fsp (count=76)
Processing file s2007VOLCAN01HAYE.fsp (count=77)
Processing file s2008KERMED01HAYE.fsp (count=78)
Processing file s2008SIMEUL01HAYE.fsp (count=79)
Processing file s2008SIMEUL01SLAD.fsp (count=80)
Processing file s2008SIMEUL02HAYE.fsp (count=81)
Processing file s2008SULAWE01SLAD.fsp (count=82)
Processing file s2008WENCHU01JIxx.fsp (count=83)
Processing file s2008WENCHU01YAGI.fsp (count=84)
Processing file s2009FIORDL01HAYE.fsp (count=85)
Processing file s2009FIORDL02HAYE.fsp (count=86)
Processing file s2009PADANG01SLAD.fsp (count=87)
Processing file s2009PADANG03HAYE.fsp (count=88)
Processing file s2009PAPUAx01HAYE.fsp (count=89)
Processing file s2009PAPUAx02HAYE.fsp (count=90)
Processing file s2009VANUAT01HAYE.fsp (count=91)
Processing file s2009VANUAT01SLAD.fsp (count=92)
Processing file s2009VANUAT02HAYE.fsp (count=93)
Processing file s2010MAULEC01DELO.fsp (count=94)
Processing file s2010MAULEC01HAYE.fsp (count=95)
Processing file s2010MAULEC01LUTT.fsp (count=96)
Processing file s2010MAULEC01POLL.fsp (count=97)
Processing file s2010MAULEC01SHAO.fsp (count=98)
Processing file s2010MAULEC01SLAD.fsp (count=99)
Processing file s2010NORTHE01HAYE.fsp (count=100)
Processing file s2010NORTHE02HAYE.fsp (count=101)
Processing file s2010NORTHE03HAYE.fsp (count=102)
Processing file s2010NORTHE04HAYE.fsp (count=103)
Processing file s2010SUMATR01HAYE.fsp (count=104)
Processing file s2010SUMATR02HAYE.fsp (count=105)
Processing file s2010VANUAT02HAYE.fsp (count=106)
Processing file s2011HONSHU01SHAO.fsp (count=107)
Processing file s2011HONSHU02SHAO.fsp (count=108)
Processing file s2011HONSHU03SHAO.fsp (count=109)
Processing file s2011HONSHU04SHAO.fsp (count=110)
Processing file s2011IBARAK01KUBO.fsp (count=111)
Processing file s2011KERMAD01HAYE.fsp (count=112)
Processing file s2011KERMAD02HAYE.fsp (count=113)
Processing file s2011KERMAD03HAYE.fsp (count=114)
Processing file s2011KERMAD04HAYE.fsp (count=115)
Processing file s2011OFFSHO01HAYE.fsp (count=116)
Processing file s2011PAKIST02HAYE.fsp (count=117)
Processing file s2011TOHOKU01AMMO.fsp (count=118)
Processing file s2011TOHOKU01HAYE.fsp (count=119)
Processing file s2011TOHOKU01IDEx.fsp (count=120)
Processing file s2011TOHOKU01LAYx.fsp (count=121)
Processing file s2011TOHOKU01WEIx.fsp (count=122)
Processing file s2011TOHOKU01YAGI.fsp (count=123)
Processing file s2011TOHOKU01YAMA.fsp (count=124)
Processing file s2011TOHOKU02WEIx.fsp (count=125)
Processing file s2011TOHOKU03WEIx.fsp (count=126)
Processing file s2011VANUAT01HAYE.fsp (count=127)
Processing file s2011VANUAT02HAYE.fsp (count=128)
Processing file s2012COSTAR01HAYE.fsp (count=129)
Processing file s2012COSTAR01LIUx.fsp (count=130)
Processing file s2012EASTOF01HAYE.fsp (count=131)
Processing file s2012MASSET01HAYE.fsp (count=132)
Processing file s2012MASSET01LAYx.fsp (count=133)
Processing file s2012MASSET01SHAO.fsp (count=134)
Processing file s2012MASSET01WEIx.fsp (count=135)
Processing file s2012NICOYA01LOPE.fsp (count=136)
Processing file s2012OAXACA01HAYE.fsp (count=137)
Processing file s2012OAXACA01WEIx.fsp (count=138)
Processing file s2012OAXACA02HAYE.fsp (count=139)
Processing file s2012OFFSHO01HAYE.fsp (count=140)
Processing file s2012OFFSHO02HAYE.fsp (count=141)
Processing file s2012SUMATR01WEIx.fsp (count=142)
Processing file s2013KHASHI01HAYE.fsp (count=143)
Processing file s2013KHASHI01WEIx.fsp (count=144)
Processing file s2013OKHOTS01YExx.fsp (count=145)
Processing file s2013SANTAC01HAYE.fsp (count=146)
Processing file s2013SANTAC01LAYx.fsp (count=147)
Processing file s2013SCOTIA01HAYE.fsp (count=148)
Processing file s2013SCOTIA02HAYE.fsp (count=149)
Processing file s2014IQUIQU01WEIx.fsp (count=150)
Processing file s2014OFFCOA01HAYE.fsp (count=151)
Processing file s2015GORKHA01HAYE.fsp (count=152)
Processing file s2015GORKHA01KOBA.fsp (count=153)
Processing file s2015GORKHA01YAGI.fsp (count=154)
Processing file s2015ILLAPE01HAYE.fsp (count=155)
Processing file s2015ILLAPE01OKUW.fsp (count=156)
Processing file s2015IRIANJ01HAYE.fsp (count=157)
Processing file s2015NEPALx01HAYE.fsp (count=158)
Processing file s2015NEWBRI02HAYE.fsp (count=159)
Processing file s2015SOLOMO02HAYE.fsp (count=160)
Processing file s2016CHILES01HAYE.fsp (count=161)
Processing file s2016KAMCHA02HAYE.fsp (count=162)
Processing file s2016MARIAN01HAYE.fsp (count=163)
Processing file s2016MARIAN02HAYE.fsp (count=164)
Processing file s2016NEARCO01HAYE.fsp (count=165)
Processing file s2016OFFE.C01HAYE.fsp (count=166)
Processing file s2016SOLOMO01HAYE.fsp (count=167)
Processing file s2016VANUAT01HAYE.fsp (count=168)
Processing file s2017SOLOMO01HAYE.fsp (count=169)
Processing file s2017SOLOMO02HAYE.fsp (count=170)

In [8]:
df_cleaned_no_nan.drop(columns=['Event', 'EventTAG', 'Dx', 'DEP', 'LAT', 'LON'], inplace=True)

C:\Users\atmad\AppData\Local\Temp\ipykernel_11220\1914421702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned_no_nan.drop(columns=['Event', 'EventTAG', 'Dx', 'DEP', 'LAT', 'LON'], inplace=True)

In [15]:
df_cleaned_no_nan['SVF'].value_counts()

SVF
asymetriccosine         49
999                     48
triang                  14
Not-Applicable           7
tsunami                  7
unknown                  6
boxcar                   5
multiwin                 5
triangle                 5
symm.traingles           4
Asymetriccosine          4
halfcosine               4
triangular               2
not-applicable           2
geodetic                 1
trapezoidal              1
smooth                   1
isosceles-triangular     1
half                     1
smoothed                 1
half-cosine              1
symm-triangles           1
box-car                  1
Name: count, dtype: int64

In [31]:
map={}
for row in df_cleaned_no_nan.drop(columns=['SVF']).iterrows():
    # print(row[1].values)
    filename = row[1].values[0][:-4]
    if filename not in map:
        map[filename] = row[1].values[1:]
    # break

In [32]:
map.keys()

dict_keys(['s1923KANTOJ01KOBA', 's1923KANTOJ01WALD', 's1944TONANK01ICHI', 's1944TONANK01KATO', 's1944TONANK01KIKU', 's1944TONANK01SATA', 's1944TONANK01TANI', 's1946NANKAI01BABA', 's1946NANKAI01KATO', 's1946NANKAI01SATA', 's1946NANKAI01TANI', 's1968HYUGAx01YAGI', 's1968TOKACH01NAGA', 's1978MIYAGI01YAMA', 's1978TABASI01HART', 's1979PETATL01MEND', 's1981PLAYAA01MEND', 's1985MICHOA01MEND', 's1985ZIHUAT01MEND', 's1994SANRIK01HAYE', 's1994SANRIK01NAGA', 's1995COLIMA01MEND', 's1995COPALA01COUR', 's1996NAZCAR01HAYE', 's1996NAZCAR01SALI', 's1996NAZCAR01SPEN', 's1998ANTARC02ANTO', 's1999CHICHI01CHIx', 's1999CHICHI01HAYE', 's1999CHICHI01MAxx', 's1999CHICHI02MAxx', 's2003COLIMA01HAYE', 's2003COLIMA01YAGI', 's2003TOKACH01HAYE', 's2003TOKACH01KOKE', 's2003TOKACH01TANI', 's2003TOKACH01YAGI', 's2003TOKACH01YAMA', 's2004SUMATR01JIxx', 's2005HONSHU01SHAO', 's2005KASHMI01SHAO', 's2005SUMATR01JIxx', 's2005SUMATR01KONC', 's2005SUMATR01SHAO', 's2006JAVAIN01HAYE', 's2006JAVAIN01YAGI', 's2006KURILI01HAYE', 's2006KURILI01JIxx', 's2006KURILI01LAYx', 's2006KURILI02SLAD', 's2006PINGTU02YENx', 's2006SOUTHE01JIxx', 's2006SOUTHE01KONC', 's2007BENGKU01GUSM', 's2007BENGKU02GUSM', 's2007BENKUL01HAYE', 's2007BENKUL01JIxx', 's2007BENKUL01KONC', 's2007BENKUL02KONC', 's2007KURILI01HAYE', 's2007MOLUCC01HAYE', 's2007PAGAII01HAYE', 's2007PAGAII01JIxx', 's2007PAGAII01KONC', 's2007PAGAII01SLAD', 's2007PISCOP01JIxx', 's2007PISCOP01KONC', 's2007SOLOMO01JIxx', 's2007SOUTHO01HAYE', 's2007TOCOPI01BEJA', 's2007TOCOPI01HAYE', 's2007TOCOPI01JIxx', 's2007TOCOPI01MOTA', 's2007TOCOPI01SLAD', 's2007TOCOPI01ZENG', 's2007TOCOPI02BEJA', 's2007TOCOPI03BEJA', 's2007VOLCAN01HAYE', 's2008KERMED01HAYE', 's2008SIMEUL01HAYE', 's2008SIMEUL01SLAD', 's2008SIMEUL02HAYE', 's2008SULAWE01SLAD', 's2008WENCHU01JIxx', 's2008WENCHU01YAGI', 's2009FIORDL01HAYE', 's2009FIORDL02HAYE', 's2009PADANG01SLAD', 's2009PADANG03HAYE', 's2009PAPUAx01HAYE', 's2009PAPUAx02HAYE', 's2009VANUAT01HAYE', 's2009VANUAT01SLAD', 's2009VANUAT02HAYE', 's2010MAULEC01DELO', 's2010MAULEC01HAYE', 's2010MAULEC01LUTT', 's2010MAULEC01POLL', 's2010MAULEC01SHAO', 's2010MAULEC01SLAD', 's2010NORTHE01HAYE', 's2010NORTHE02HAYE', 's2010NORTHE03HAYE', 's2010NORTHE04HAYE', 's2010SUMATR01HAYE', 's2010SUMATR02HAYE', 's2010VANUAT02HAYE', 's2011HONSHU01SHAO', 's2011HONSHU02SHAO', 's2011HONSHU03SHAO', 's2011HONSHU04SHAO', 's2011IBARAK01KUBO', 's2011KERMAD01HAYE', 's2011KERMAD02HAYE', 's2011KERMAD03HAYE', 's2011KERMAD04HAYE', 's2011OFFSHO01HAYE', 's2011PAKIST02HAYE', 's2011TOHOKU01AMMO', 's2011TOHOKU01HAYE', 's2011TOHOKU01IDEx', 's2011TOHOKU01LAYx', 's2011TOHOKU01WEIx', 's2011TOHOKU01YAGI', 's2011TOHOKU01YAMA', 's2011TOHOKU02WEIx', 's2011TOHOKU03WEIx', 's2011VANUAT01HAYE', 's2011VANUAT02HAYE', 's2012COSTAR01HAYE', 's2012COSTAR01LIUx', 's2012EASTOF01HAYE', 's2012MASSET01HAYE', 's2012MASSET01LAYx', 's2012MASSET01SHAO', 's2012MASSET01WEIx', 's2012NICOYA01LOPE', 's2012OAXACA01HAYE', 's2012OAXACA01WEIx', 's2012OAXACA02HAYE', 's2012OFFSHO01HAYE', 's2012OFFSHO02HAYE', 's2012SUMATR01WEIx', 's2013KHASHI01HAYE', 's2013KHASHI01WEIx', 's2013OKHOTS01YExx', 's2013SANTAC01HAYE', 's2013SANTAC01LAYx', 's2013SCOTIA01HAYE', 's2013SCOTIA02HAYE', 's2014IQUIQU01WEIx', 's2014OFFCOA01HAYE', 's2015GORKHA01HAYE', 's2015GORKHA01KOBA', 's2015GORKHA01YAGI', 's2015ILLAPE01HAYE', 's2015ILLAPE01OKUW', 's2015IRIANJ01HAYE', 's2015NEPALx01HAYE', 's2015NEWBRI02HAYE', 's2015SOLOMO02HAYE', 's2016CHILES01HAYE', 's2016KAMCHA02HAYE', 's2016MARIAN01HAYE', 's2016MARIAN02HAYE', 's2016NEARCO01HAYE', 's2016OFFE.C01HAYE', 's2016SOLOMO01HAYE', 's2016VANUAT01HAYE', 's2017SOLOMO01HAYE', 's2017SOLOMO02HAYE'])

In [ ]:
map={}
for row in df_cleaned_no_nan.iterrows():
    for col in df_cleaned_no_nan.columns:
        if col != 'filename':
            col_name = col
            col_value = row[1][col]
            if row[1]['filename'] not in map:
                map[row[1]['filename']] = ""
            map[row[1]['filename']] += f"The value of the earthquake fault plane parameter \"{col_name}\" is {col_value}.\n"

In [12]:
print(map['s1923KANTOJ01KOBA.fsp'])

The value of the earthquake fault plane parameter "Event" is Kanto (Japan).
The value of the earthquake fault plane parameter "EventTAG" is s1923KANTOJ01KOBA.
The value of the earthquake fault plane parameter "LAT" is 35.4.
The value of the earthquake fault plane parameter "LON" is 139.2.
The value of the earthquake fault plane parameter "DEP" is 14.6.
The value of the earthquake fault plane parameter "LEN_f" is 130.0.
The value of the earthquake fault plane parameter "WID" is 70.0.
The value of the earthquake fault plane parameter "Mw" is 8.08.
The value of the earthquake fault plane parameter "Mo" is 1.46e+21.
The value of the earthquake fault plane parameter "STRK" is 290.0.
The value of the earthquake fault plane parameter "DIP" is 25.0.
The value of the earthquake fault plane parameter "RAKE" is 140.0.
The value of the earthquake fault plane parameter "Htop" is 2.0.
The value of the earthquake fault plane parameter "HypX" is 110.5.
The value of the earthquake fault plane parameter "HypZ" is 35.0.
The value of the earthquake fault plane parameter "avTr" is 10.5.
The value of the earthquake fault plane parameter "avVr" is 2.6.
The value of the earthquake fault plane parameter "Nx" is 10.0.
The value of the earthquake fault plane parameter "Nz" is 7.0.
The value of the earthquake fault plane parameter "Fmin" is 0.02.
The value of the earthquake fault plane parameter "Fmax" is 0.4.
The value of the earthquake fault plane parameter "Dx" is 13.0.
The value of the earthquake fault plane parameter "Dz" is 10.0.
The value of the earthquake fault plane parameter "Ntw" is 1.0.
The value of the earthquake fault plane parameter "Nsg" is 1.0.
The value of the earthquake fault plane parameter "LEN_inv" is 1.5.
The value of the earthquake fault plane parameter "SHF" is 0.0.
The value of the earthquake fault plane parameter "SVF" is triang.
The value of the earthquake fault plane parameter "SGM-Data" is 3.0.
The value of the earthquake fault plane parameter "TELE-Data" is 5.0.
The value of the earthquake fault plane parameter "GPS-Data" is 0.0.
The value of the earthquake fault plane parameter "SGM-PHImx" is 240.0.
The value of the earthquake fault plane parameter "TELE-PHImx" is 200.0.
The value of the earthquake fault plane parameter "TRIL-PHImx" is 999.0.
The value of the earthquake fault plane parameter "LEVEL-PHImx" is 999.0.
The value of the earthquake fault plane parameter "GPS-PHImx" is 0.0.
The value of the earthquake fault plane parameter "SGM-Rmin" is 90.0.
The value of the earthquake fault plane parameter "TELE-Rmin" is 60.0.
The value of the earthquake fault plane parameter "TRIL-Rmin" is 999.0.
The value of the earthquake fault plane parameter "LEVEL-Rmin" is 999.0.
The value of the earthquake fault plane parameter "GPS-Rmin" is 0.0.

In [13]:
import json

# Export the map dictionary to a JSON file
with open(r'Dataset/texts_cleaned.json', 'w', encoding='utf-8') as f:
    json.dump(map, f, indent=2, ensure_ascii=False)

print(f"Map exported to earthquake_parameters.json successfully!")

Map exported to earthquake_parameters.json successfully!

In [41]:
np.save(r'Dataset/text_vec.npy', a)

In [40]:
a = np.load(r'Dataset/text_vec.npy', allow_pickle=True).item()

# Convert text vectors to float32
for key in a:
    if isinstance(a[key], np.ndarray) and a[key].dtype != np.float32:
        a[key] = a[key].astype(np.float32)

In [42]:
a

{'s1923KANTOJ01KOBA': array([1.3000000e+02, 7.0000000e+01, 8.0799999e+00, 1.4600000e+21,
        2.9000000e+02, 2.5000000e+01, 1.4000000e+02, 2.0000000e+00,
        1.1050000e+02, 3.5000000e+01, 1.0500000e+01, 2.5999999e+00,
        1.0000000e+01, 7.0000000e+00, 2.0000000e-02, 4.0000001e-01,
        1.0000000e+01, 1.0000000e+00, 1.0000000e+00, 1.5000000e+00,
        0.0000000e+00, 3.0000000e+00, 5.0000000e+00, 0.0000000e+00,
        2.4000000e+02, 2.0000000e+02, 9.9900000e+02, 9.9900000e+02,
        0.0000000e+00, 9.0000000e+01, 6.0000000e+01, 9.9900000e+02,
        9.9900000e+02, 0.0000000e+00, 1.1888526e+02], dtype=float32),
 's1923KANTOJ01WALD': array([1.3000000e+02, 7.0000000e+01, 7.9499998e+00, 9.3299997e+20,
        2.9000000e+02, 2.5000000e+01, 1.3880832e+02, 2.0000000e+00,
        1.0500000e+02, 2.9799999e+01, 8.0000000e+00, 3.0000000e+00,
        1.0000000e+01, 7.0000000e+00, 0.0000000e+00, 7.0000000e-02,
        1.0000000e+01, 3.0000000e+00, 1.0000000e+00, 4.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 6.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.6500000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 6.9800003e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0400107e+02], dtype=float32),
 's1944TONANK01ICHI': array([2.2000000e+02, 1.4000000e+02, 8.0400000e+00, 1.3100000e+21,
        2.3500000e+02, 2.0000000e+01, 8.2000000e+01, 2.0000000e+00,
        1.9000000e+02, 1.1000000e+02, 2.2500000e+01, 2.5000000e+00,
        1.1000000e+01, 7.0000000e+00, 0.0000000e+00, 5.0000000e-01,
        2.0000000e+01, 8.0000000e+00, 1.0000000e+00, 5.0000000e+00,
        2.5000000e+00, 1.3000000e+01, 1.0000000e+01, 0.0000000e+00,
        1.8000000e+02, 1.0000000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 3.0000000e+01, 6.0000000e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.7110764e+02], dtype=float32),
 's1944TONANK01KATO': array([2.4000000e+02, 1.8000000e+02, 8.1999998e+00, 2.7999999e+21,
        2.4000000e+02, 9.6000004e+00, 1.0840000e+02, 1.5000000e+01,
        1.5000000e+02, 1.2000000e+02, 0.0000000e+00, 0.0000000e+00,
        4.0000000e+00, 3.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        6.0000000e+01, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 7.9597894e+02], dtype=float32),
 's1944TONANK01KIKU': array([1.40000e+02, 8.00000e+01, 7.99000e+00, 1.08000e+21, 2.25000e+02,
        1.50000e+01, 7.90000e+01, 1.18800e+01, 1.30000e+02, 7.00000e+01,
        1.65000e+01, 3.10000e+00, 7.00000e+00, 4.00000e+00, 5.00000e-02,
        5.00000e-01, 2.00000e+01, 1.00000e+01, 1.00000e+00, 3.00000e+00,
        1.50000e+00, 6.00000e+00, 0.00000e+00, 0.00000e+00, 1.75000e+02,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.50000e+02,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 2.85456e+02],
       dtype=float32),
 's1944TONANK01SATA': array([2.7000000e+02, 1.8000000e+02, 8.1000004e+00, 2.0000000e+21,
        2.4000000e+02, 1.5000000e+01, 1.1000000e+02, 1.5000000e+01,
        1.5000000e+02, 1.2000000e+02, 0.0000000e+00, 0.0000000e+00,
        3.0000000e+00, 3.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        6.0000000e+01, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0775745e+03], dtype=float32),
 's1944TONANK01TANI': array([3.1500000e+02, 1.8000000e+02, 8.1000004e+00, 2.0000000e+21,
        2.4000000e+02, 8.0000000e+00, 1.1000000e+02, 1.0000000e+00,
        2.0250000e+02, 1.3500000e+02, 0.0000000e+00, 0.0000000e+00,
        7.0000000e+00, 4.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.5000000e+01, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 7.2521234e+02], dtype=float32),
 's1946NANKAI01BABA': array([3.600000e+02, 1.800000e+02, 8.400000e+00, 4.900000e+21,
        2.500000e+02, 1.200000e+01, 1.200000e+02, 1.000000e+00,
        8.500000e+01, 4.000000e+01, 0.000000e+00, 0.000000e+00,
        8.000000e+00, 4.000000e+00, 0.000000e+00, 0.000000e+00,
        4.500000e+01, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 8.886131e+02], dtype=float32),
 's1946NANKAI01KATO': array([3.600000e+02, 1.800000e+02, 8.300000e+00, 4.000000e+21,
        2.500000e+02, 1.710000e+01, 1.192000e+02, 1.000000e+00,
        9.500000e+01, 4.000000e+01, 0.000000e+00, 0.000000e+00,
        6.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
        6.000000e+01, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.045476e+03], dtype=float32),
 's1946NANKAI01SATA': array([3.6000000e+02, 1.8000000e+02, 8.3100004e+00, 3.3099999e+21,
        2.5000000e+02, 1.0000000e+01, 1.2000000e+02, 5.0000000e+00,
        9.0000000e+01, 4.0000000e+01, 0.0000000e+00, 0.0000000e+00,
        4.0000000e+00, 3.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        6.0000000e+01, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 9.9900000e+02, 9.9900000e+02,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 9.9900000e+02,
        9.9900000e+02, 0.0000000e+00, 1.6583402e+03], dtype=float32),
 's1946NANKAI01TANI': array([3.600000e+02, 1.800000e+02, 8.400000e+00, 4.510000e+21,
        2.500000e+02, 1.300000e+01, 1.200000e+02, 1.000000e+00,
        9.000000e+01, 4.500000e+01, 0.000000e+00, 0.000000e+00,
        8.000000e+00, 4.000000e+00, 0.000000e+00, 0.000000e+00,
        4.500000e+01, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 8.336853e+02], dtype=float32),
 's1968HYUGAx01YAGI': array([7.2000000e+01, 6.3000000e+01, 7.5300002e+00, 2.2200000e+20,
        2.2700000e+02, 1.2000000e+01, 9.0000000e+01, 1.0320000e+01,
        3.1500000e+01, 2.2500000e+01, 1.2000000e+01, 2.8000000e+00,
        8.0000000e+00, 7.0000000e+00, 9.9900000e+02, 9.9900000e+02,
        9.0000000e+00, 1.0000000e+00, 1.0000000e+00, 9.9900000e+02,
        0.0000000e+00, 9.9900000e+02, 0.0000000e+00, 0.0000000e+00,
        9.9900000e+02, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 9.9900000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.1330657e+01], dtype=float32),
 's1968TOKACH01NAGA': array([2.400000e+02, 1.200000e+02, 8.350000e+00, 3.760000e+21,
        1.560000e+02, 2.000000e+01, 9.000000e+01, 5.580000e+00,
        1.500000e+02, 1.000000e+01, 1.200000e+01, 1.900000e+00,
        1.200000e+01, 6.000000e+00, 3.000000e-02, 4.000000e-01,
        2.000000e+01, 1.000000e+00, 1.000000e+00, 9.990000e+02,
        0.000000e+00, 9.990000e+02, 9.990000e+02, 0.000000e+00,
        9.990000e+02, 9.990000e+02, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 9.990000e+02, 9.990000e+02, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.923678e+02], dtype=float32),
 's1978MIYAGI01YAMA': array([8.0000000e+01, 7.0000000e+01, 7.6100001e+00, 2.9100000e+20,
        2.0000000e+02, 2.0000000e+01, 9.1327614e+01, 3.5279999e+01,
        5.5000000e+01, 5.0000000e+00, 9.9900000e+02, 9.9900000e+02,
        8.0000000e+00, 7.0000000e+00, 2.0000000e-02, 5.0000000e-01,
        1.0000000e+01, 1.0000000e+00, 1.0000000e+00, 9.9900000e+02,
        0.0000000e+00, 8.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        2.1000000e+02, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.5000000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 5.5745453e+01], dtype=float32),
 's1978TABASI01HART': array([9.5000000e+01, 4.5000000e+01, 7.0900002e+00, 4.8199999e+19,
        3.3000000e+02, 2.5000000e+01, 1.2500000e+02, 1.0000000e+00,
        2.0000000e+01, 1.0500000e+01, 6.9999999e-01, 2.5000000e+00,
        2.0000000e+01, 1.0000000e+01, 2.0000000e-01, 2.0000000e+00,
        4.5000000e+00, 1.0000000e+00, 1.0000000e+00, 6.9999999e-01,
        0.0000000e+00, 3.0000000e+00, 1.0000000e+01, 0.0000000e+00,
        1.8900000e+02, 1.8000000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.2000000e+01, 4.0099998e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.7440592e+01], dtype=float32),
 's1979PETATL01MEND': array([1.200000e+02, 1.200000e+02, 7.390000e+00, 1.370000e+20,
        2.930000e+02, 1.400000e+01, 9.000000e+01, 2.000000e+00,
        6.170000e+01, 5.370000e+01, 1.000000e+01, 3.300000e+00,
        1.200000e+01, 1.200000e+01, 1.000000e-02, 2.000000e-01,
        1.000000e+01, 1.000000e+01, 1.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 1.500000e+01, 0.000000e+00,
        0.000000e+00, 9.500000e+01, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 4.520000e+01, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 4.233725e+00], dtype=float32),
 's1981PLAYAA01MEND': array([6.0000000e+01, 7.0000000e+01, 7.2500000e+00, 8.4900004e+19,
        3.0000000e+02, 1.4000000e+01, 9.0000000e+01, 6.0000000e+00,
        3.2500000e+01, 3.4500000e+01, 1.0000000e+00, 2.5999999e+00,
        1.2000000e+01, 1.4000000e+01, 0.0000000e+00, 2.0000000e-01,
        5.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.5000000e+01, 0.0000000e+00,
        0.0000000e+00, 1.0900000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.0500000e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.1647887e+00], dtype=float32),
 's1985MICHOA01MEND': array([1.8000000e+02, 1.3900000e+02, 8.0100002e+00, 1.1500000e+21,
        3.0000000e+02, 1.4000000e+01, 6.1305634e+01, 6.0000000e+00,
        1.2500000e+02, 4.2000000e+01, 6.0000000e+00, 2.5999999e+00,
        1.2000000e+01, 1.0000000e+01, 0.0000000e+00, 5.0000000e-01,
        1.3900000e+01, 3.0000000e+00, 1.0000000e+00, 2.0000000e+00,
        0.0000000e+00, 4.0000000e+00, 1.3000000e+01, 0.0000000e+00,
        2.4300000e+02, 2.0300000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.8200001e+01, 9.9900000e+02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.2084403e+02], dtype=float32),
 's1985ZIHUAT01MEND': array([9.0000000e+01, 9.0000000e+01, 7.4200001e+00, 1.5300000e+20,
        3.0000000e+02, 1.4000000e+01, 1.0000000e+02, 1.2000000e+01,
        5.4750000e+01, 3.3750000e+01, 1.0000000e+00, 2.5999999e+00,
        1.2000000e+01, 1.2000000e+01, 0.0000000e+00, 5.0000000e-01,
        7.5000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.4000000e+01, 0.0000000e+00,
        0.0000000e+00, 1.1700000e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.1000000e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.8249542e+01], dtype=float32),
 's1994SANRIK01HAYE': array([2.1000000e+02, 1.5010001e+02, 7.7199998e+00, 4.9200000e+20,
        1.8300000e+02, 1.5000000e+01, 7.2445358e+01, 8.6199999e+00,
        1.1250000e+02, 6.7150002e+01, 4.3000002e+00, 2.5000000e+00,
        1.4000000e+01, 1.9000000e+01, 0.0000000e+00, 1.0000000e+00,
        7.9000001e+00, 5.0000000e+00, 1.0000000e+00, 3.4000001e+00,
        1.7000000e+00, 0.0000000e+00, 7.2000000e+01, 0.0000000e+00,
        0.0000000e+00, 6.9000000e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.6919998e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.5244127e+01], dtype=float32),
 's1994SANRIK01NAGA': array([1.100000e+02, 1.400000e+02, 7.700000e+00, 3.990000e+20,
        1.840000e+02, 6.000000e+00, 9.000000e+01, 7.390000e+00,
        4.500000e+01, 2.500000e+01, 1.200000e+01, 2.400000e+00,
        1.100000e+01, 1.400000e+01, 3.000000e-02, 4.000000e-01,
        1.000000e+01, 9.990000e+02, 1.000000e+00, 9.990000e+02,
        9.990000e+02, 9.990000e+02, 0.000000e+00, 0.000000e+00,
        9.990000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 9.990000e+02, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 8.203702e+01], dtype=float32),
 's1995COLIMA01MEND': array([2.00000000e+02, 1.00000000e+02, 7.96000004e+00, 9.67000035e+20,
        3.09000000e+02, 1.40000000e+01, 9.20000000e+01, 3.00000000e+00,
        5.10999985e+01, 5.60000000e+01, 2.00000000e+00, 2.79999995e+00,
        2.00000000e+01, 1.00000000e+01, 1.99999996e-02, 5.00000000e-01,
        1.00000000e+01, 1.00000000e+01, 1.00000000e+00, 2.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.80000000e+01, 0.00000000e+00,
        0.00000000e+00, 9.70000000e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 9.99000000e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00102516e+02], dtype=float32),
 's1995COPALA01COUR': array([7.500000e+01, 5.500000e+01, 7.300000e+00, 8.900000e+19,
        2.890000e+02, 1.100000e+01, 7.500000e+01, 1.075300e+01,
        3.747000e+01, 2.710000e+01, 2.500000e+00, 2.500000e+00,
        1.500000e+01, 1.100000e+01, 9.990000e+02, 5.000000e-01,
        5.000000e+00, 9.990000e+02, 1.000000e+00, 3.000000e+00,
        9.990000e+02, 2.000000e+00, 0.000000e+00, 0.000000e+00,
        9.990000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 9.990000e+02, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 2.057051e+00], dtype=float32),
 's1996NAZCAR01HAYE': array([2.0000000e+02, 1.0500000e+02, 7.6999998e+00, 4.6100000e+20,
        3.1200000e+02, 3.3000000e+01, 6.0627518e+01, 2.9999999e-02,
        1.5500000e+02, 3.8500000e+01, 3.8000000e+00, 2.0000000e+00,
        2.0000000e+01, 1.5000000e+01, 0.0000000e+00, 1.0000000e+00,
        7.0000000e+00, 5.0000000e+00, 1.0000000e+00, 3.2000000e+00,
        1.6000000e+00, 0.0000000e+00, 2.8000000e+01, 0.0000000e+00,
        0.0000000e+00, 7.4000000e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.3560001e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.1140102e+02], dtype=float32),
 's1996NAZCAR01SALI': array([1.8000000e+02, 1.2000000e+02, 7.8400002e+00, 6.5700003e+20,
        3.0700000e+02, 3.0000000e+01, 4.6923435e+01, 8.0000000e+00,
        1.5000000e+02, 5.0000000e+01, 1.2500000e+01, 2.7000000e+00,
        9.0000000e+00, 6.0000000e+00, 0.0000000e+00, 5.0000000e-01,
        2.0000000e+01, 4.0000000e+00, 1.0000000e+00, 5.0000000e+00,
        2.5000000e+00, 0.0000000e+00, 1.3000000e+01, 0.0000000e+00,
        0.0000000e+00, 7.5000000e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 9.9900000e+02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.4000000e+02], dtype=float32),
 's1996NAZCAR01SPEN': array([3.0000000e+02, 1.2000000e+02, 8.0600004e+00, 1.3800000e+21,
        3.1200000e+02, 3.3000000e+01, 5.2000000e+01, 1.0000000e+00,
        1.5000000e+02, 3.8000000e+01, 1.0000000e+01, 3.0000000e+00,
        2.5000000e+01, 1.0000000e+01, 9.9999998e-03, 1.0000000e+00,
        1.2000000e+01, 1.0000000e+01, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.8000000e+01, 0.0000000e+00,
        0.0000000e+00, 6.2000000e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.0000000e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.2204952e+01], dtype=float32),
 's1998ANTARC02ANTO': array([ 9.00000e+01,  6.00000e+01,  7.76000e+00,  4.85000e+20,
         2.95000e+02,  2.70000e+01, -4.20000e+01,  1.00000e-02,
         8.80000e+01,  1.20000e+01,  9.99000e+02,  2.20000e+00,
         1.80000e+01,  1.20000e+01,  0.00000e+00,  1.00000e-01,
         5.00000e+00,  1.00000e+00,  1.00000e+00,  9.99000e+02,
         0.00000e+00,  0.00000e+00,  2.10000e+01,  0.00000e+00,
         0.00000e+00,  5.70000e+01,  0.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  3.62000e+01,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  4.51634e+01], dtype=float32),
 's1999CHICHI01CHIx': array([1.1200000e+02, 4.5500000e+01, 7.6799998e+00, 3.7300001e+20,
        5.0000000e+00, 3.0000000e+01, 6.1568878e+01, 8.9999998e-01,
        3.5000000e+01, 1.6000000e+01, 1.1500000e+01, 2.5999999e+00,
        3.2000000e+01, 1.3000000e+01, 0.0000000e+00, 5.0000000e-01,
        3.5000000e+00, 1.0000000e+01, 1.0000000e+00, 3.0000000e+00,
        1.5000000e+00, 2.1000000e+01, 0.0000000e+00, 0.0000000e+00,
        3.8000000e+01, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.5009247e+01], dtype=float32),
 's1999CHICHI01HAYE': array([1.4400000e+02, 5.0849998e+01, 7.5799999e+00, 3.0400001e+20,
        3.0000000e+00, 3.0000000e+01, 6.0529274e+01, 1.1000000e-01,
        4.4000000e+01, 1.9770000e+01, 2.9000001e+00, 1.3000000e+00,
        1.8000000e+01, 9.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        5.6500001e+00, 5.0000000e+00, 1.0000000e+00, 2.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 6.5000000e+01, 0.0000000e+00,
        0.0000000e+00, 5.3000000e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.3799999e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 4.4970688e+01], dtype=float32),
 's1999CHICHI01MAxx': array([1.0000000e+02, 4.5000000e+01, 7.6900001e+00, 3.7900000e+20,
        5.0000000e+00, 3.0000000e+01, 5.5167667e+01, 9.9999998e-03,
        3.2500000e+01, 1.7500000e+01, 1.2000000e+01, 2.5000000e+00,
        2.0000000e+01, 9.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        5.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 2.1000000e+01, 2.2000000e+01, 1.3100000e+02,
        3.0000000e+01, 2.7000000e+01, 3.5000000e+01, 0.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 5.0000000e+01, 5.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.7633421e+01], dtype=float32),
 's1999CHICHI02MAxx': array([1.0500000e+02, 4.0000000e+01, 7.6900001e+00, 3.8700002e+20,
        5.0000000e+00, 3.0000000e+01, 6.4927345e+01, 9.9999998e-03,
        3.2500000e+01, 1.2500000e+01, 1.2000000e+01, 2.5000000e+00,
        2.1000000e+01, 8.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        5.0000000e+00, 1.2000000e+01, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 2.1000000e+01, 2.2000000e+01, 1.3100000e+02,
        3.0000000e+01, 2.7000000e+01, 3.5000000e+01, 0.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 5.0000000e+01, 5.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.0463381e+01], dtype=float32),
 's2003COLIMA01HAYE': array([1.0500000e+02, 1.6430000e+02, 7.4600000e+00, 2.0200001e+20,
        3.0400000e+02, 1.6000000e+01, 1.0918647e+02, 1.3500000e+00,
        5.2500000e+01, 8.2150002e+01, 2.0999999e+00, 2.0000000e+00,
        1.5000000e+01, 3.1000000e+01, 0.0000000e+00, 1.0000000e+00,
        5.3000002e+00, 5.0000000e+00, 1.0000000e+00, 1.6000000e+00,
        8.0000001e-01, 0.0000000e+00, 4.8000000e+01, 0.0000000e+00,
        0.0000000e+00, 6.6000000e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.3919998e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.5662801e+00], dtype=float32),